---
- name: input user
  set_fact:
    input_user: '{{ input_user | default(homebrew_user) | default(ansible_user_id) }}'
  tags:
    - input

- become: '{{ (input_user != ansible_user_id) | bool }}'
  become_user: '{{ input_user }}'
  block:
    - name: presshold enabled
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: ApplePressAndHoldEnabled
        type: bool
        value: '{{ input_press_and_hold_enabled }}'
        state: present
      tags:
        - input

    - name: keyrepeat rate
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: KeyRepeat
        type: int
        value: '{{ input_key_repeat }}'
        state: present
      tags:
        - input

    - name: keyrepeat initial
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: InitialKeyRepeat
        type: int
        value: '{{ input_initial_key_repeat }}'
        state: present
      tags:
        - input

    - name: natural scrolling
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.swipescrolldirection
        type: int
        value: '{{ input_natural_scrolling }}'
        state: present
      tags:
        - input

    - name: force click
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.trackpad.forceClick
        type: int
        value: '{{ input_force_click }}'
        state: present
      tags:
        - input

    - name: trackpad scaling
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: com.apple.trackpad.scaling
        type: float
        value: '{{ input_trackpad_scaling }}'
        state: present
      tags:
        - input

    - name: trackpad tapclick
      # notify:
      #   - kill input
      osx_defaults:
        domain: com.apple.driver.AppleBluetoothMultitouch.trackpad
        key: Clicking
        type: int
        value: '{{ input_trackpad_tap_click }}'
        state: present
      tags:
        - input

    - name: wipe replacement
      # notify:
      #   - kill input
      osx_defaults:
        domain: NSGlobalDomain
        key: NSUserDictionaryReplacementItems
        type: array
        value: []
        state: present
      tags:
        - input

...
